Updated build-system. Does this help you khz?

diff --git a/admin/Makefile.common b/admin/Makefile.common
--- a/admin/Makefile.common
+++ b/admin/Makefile.common
@@ -1,10 +1,14 @@
 
+SHELL=/bin/sh
+
 cvs:
 	@if grep '$$(top_srcdir)/acinclude.m4:' Makefile.am >/dev/null; then \
 	  echo "*** Creating acinclude.m4" ;\
 	  rm -f acinclude.m4 configure.files ;\
 	  $(MAKE) -f Makefile.am top_srcdir=. acinclude.m4 ;\
 	fi
+	@echo "!!! If you get recursion errors from autoconf, it is advisable to set the"
+	@echo "    environment variable M4 to something including \"--nesting-limit=500\""
 	@if test -r configure.in.in; then \
 	  rm -f subdirs configure.in ;\
 	  echo "*** Creating list of subdirectories" ;\
@@ -14,8 +18,6 @@ cvs:
 	fi
 	@echo "*** Creating aclocal.m4"
 	@aclocal
-	@echo "*** Creating config.h template"
-	@autoheader
 	@echo "*** Creating configure"
 	@autoconf
 	@if test -r configure.in.in ; then \
@@ -28,6 +30,10 @@ cvs:
 	@if grep '} \$$ac_kw foo' configure >/dev/null 2>&1; then perl -p -i -e "s/ac_kw foo/ac_kw int foo/" configure; fi
 #David's hack for autoconf bug when $INSTALL is set
 	@perl -pi -e 'if (/\[\/\$$\]\*. INSTALL=/) { print $$_ ; $$_ = "\"\") ;;\n"; }' configure
+	@if egrep "^AM_CONFIG_HEADER" configure.in >/dev/null 2>&1; then \
+	  echo "*** Creating config.h template" ;\
+		autoheader ;\
+	fi
 	@echo "*** Creating Makefile templates"
 	@automake
 	@echo "*** Postprocessing Makefile templates"
@@ -81,34 +87,27 @@ cvs-clean:
 	  echo "You don't have a toplevel CVS directory."; \
 	  echo "You most certainly didn't use cvs to get these sources."; \
 	  echo "But this function depends on cvs's information."; \
-	  exit 1 ;\
-	fi;\
-	pwd=`pwd` ;\
-	dirs=`find . -type d | grep -v CVS | sed -e "s#^./##"` ;\
-	for i in $$dirs; do \
-	  if test ! -d "$$pwd/$$i/CVS"; then \
-	    echo "D $$i" ;\
-	    rm -rf "$$pwd/$$i"; \
-	    continue; \
-	  fi ;\
-	  cd $$pwd/$$i ;\
-	  for f in * .*; do \
-	    if test ! -d "$$f"; then \
-	      if grep "^/$$f/" CVS/Entries > /dev/null; then \
-		a="b"; \
-	      else \
-	        echo "F $$i/$$f"; \
-		rm -f "$$pwd/$$i/$$f"; \
-	      fi; \
-	    fi ; \
-	  done; \
-	done
+	  exit 1; \
+	fi; \
+	LC_COLLATE=C; export LC_COLLATE; \
+	pwd=`pwd`; \
+	incvs=$$pwd/.incvs; indir=$$pwd/.indir; \
+	for i in `find . -follow -type d ! -name CVS | sed -e "s#^./##"`; do \
+	  if test -d $$pwd/$$i; then \
+	    cd $$pwd/$$i && \
+	    sed -ne 's#^/\([^/]*\)/.*$$#\1#p;s#^D/\([^/]*\)/.*$$#\1/#p' < CVS/Entries | sort -t / +0 -1 > $$incvs && \
+	    ls -LAF | sed -ne '\#^CVS/$$#d;\#^.incvs$$#d;\#^.indir$$#d;s#^\(.*\)[*=|>]$$#\1#;p' > $$indir && \
+	    eval "`diff $$incvs $$indir | sed -ne 's#^> \(.*\)/$$#echo "D $$i/\1";rm -rf "$$pwd/$$i/\1"#p;s#^> \(.*[^/]\)$$#echo "F $$i/\1";rm -f "$$pwd/$$i/\1"#p'`"; \
+	  fi; \
+	done; \
+	rm -f $$incvs $$indir
 
 
 # The Makefiles have to be sorted for slashes, since configure creates
 # only one directory per Makefile not the whole hierarchy
 configure.in: configure.files $(shell test -f configure.files && cat configure.files) subdirs
 	@rm -f configure.in configure.in.new ;\
+	kde_use_qt_param= ; \
 	cat `cat configure.files | egrep -v "^configure.in.bot"` >> configure.in.new ;\
 	echo "KDE_CREATE_SUBDIRSLIST" >> configure.in.new ;\
 	echo "AC_OUTPUT( \\" >> configure.in.new ;\
@@ -132,7 +131,13 @@ configure.in: configure.files $(shell test -f configure.files && cat configure.f
 	echo ")" >> configure.in.new
 	@modulename= ;\
 	if test -f configure.in.in; then \
-	   if head -2 configure.in.in | egrep "^#MIN_CONFIG$$" > /dev/null; then \
+	   if head -2 configure.in.in | egrep "^#MIN_CONFIG\(.*\)$$" > /dev/null; then \
+	      line=`egrep "^#MIN_CONFIG\(" configure.in.in` ;\
+	      if test -n "$$line"; then \
+		  kde_use_qt_param=`echo $$line | sed -e "s/#MIN_CONFIG(\(.*\))/\1/"` ;\
+	      fi ;\
+	   fi ;\
+	   if head -2 configure.in.in | egrep "^#MIN_CONFI(G|G\(.*\))$$" > /dev/null; then \
 	      line=`egrep "^AM_INIT_AUTOMAKE\(" configure.in.in` ;\
 	      if test -n "$$line"; then \
 		  modulename=`echo $$line | sed -e "s#AM_INIT_AUTOMAKE(\([^,]*\),.*#\1#"` ;\
@@ -146,8 +151,12 @@ configure.in: configure.files $(shell test -f configure.files && cat configure.f
 	   modulename=`pwd`; modulename=`basename $$modulename`; \
 	fi ;\
 	if test -z "$$VERSION" || test "$$VERSION" = "@VERSION@"; then \
-	     VERSION="\"2.2alpha2\"";  \
+	     VERSION="\"2.91\"";  \
 	fi ;\
+	if test -n "$$kde_use_qt_param"; then \
+	      sed -e "s#^dnl KDE_USE_QT#KDE_USE_QT($$kde_use_qt_param)#" configure.in.new > configure.in \
+		  && mv configure.in configure.in.new ;\
+	fi ; \
 	sed -e "s#@MODULENAME@#$$modulename#" configure.in.new | \
 		sed -e "s#@VERSION@#$$VERSION#" > configure.in
 	@if test -f configure.in.bot ; then cat configure.in.bot >> configure.in ; fi
@@ -159,7 +168,7 @@ configure.files: subdirs
 	  if test -x $$i/admin; then admindir=$$i/admin; break; fi; \
 	done ;\
 	rm -rf configure.files ;\
-	if test -f configure.in.in && head -2 configure.in.in | egrep "^#MIN_CONFIG$$" > /dev/null; then \
+	if test -f configure.in.in && head -2 configure.in.in | egrep "^#MIN_CONFI(G|G\(.*\))$$" > /dev/null; then \
 		echo $$admindir/configure.in.min >> configure.files  ;\
 	fi
 	@test -f configure.in.in && echo configure.in.in >> configure.files
@@ -191,14 +200,14 @@ subdirs:
 	     fi ;\
 	   fi; \
 	done ;\
-	rm -f SUBDIRS ;\
+	rm -f _SUBDIRS ;\
 	for i in $$dirs; do \
-	echo $$i >> ./SUBDIRS; \
+	echo $$i >> ./_SUBDIRS; \
 	done
-	@if test -r subdirs && diff subdirs SUBDIRS > /dev/null; then \
-	  rm -f SUBDIRS; \
+	@if test -r subdirs && diff subdirs _SUBDIRS > /dev/null; then \
+	  rm -f _SUBDIRS; \
 	fi
-	@test -r SUBDIRS && mv SUBDIRS subdirs || true
+	@test -r _SUBDIRS && mv _SUBDIRS subdirs || true
 
 package-merge:
 	@catalogs='$(POFILES)'; \
@@ -287,3 +296,6 @@ test:
 	perl -e '$$mes=0; while (<STDIN>) { if (/^messages:/) { $$mes=1; print $$_; next; } if ($$mes) { if (! /^\t/) { exit(0); } if (/$$\\(XGETTEXT\)/ && / -o/) { s/ -o/ _translatorinfo.cpp -o/ } print $$_;  } }' < Makefile.am
 
 .SILENT:
+
+.PHONY: cvs test dist cvs-clean subdirs package-merge package-messages
+
